10 REM THIS IS A COMMENT
20 REM THERE ARE NO BLOCK COMMENTS IN BASIC V2 =(

30 REM NOTE LINE NUMBERS, THEY CAN BE ANY NUMBER IN ANY ORDER
31 REM THEY ARE REQUIRED AT THE START OF EACH PROGRAM LINE
34 PRINT "LIKE THIS"
32 PRINT "OR LIKE THIS"
35 REM THEY ALSO FUNCTION AS LABELS TO JUMP TO
36 PRINT "JUMPING TO LINE 60" :GOTO 60
37 REM STANDARD CONVENTION IS TO INCREMENT LINE NUMBERS BY 10
38 REM ...MOST OF THE TIME

40 REM THE REASON EVERYTHING IS CAPITALIZED IS BECAUSE THE COMMANDER X16
41 REM USES PETSCII, AND THUS TREATS LOWER CASES AS 'SPECIAL CHARACTERS'
42 PRINT "UPPER CASE HELLO WORLD"
43 PRINT "LOWER CASE hello world"

50 REM YOU CAN HAVE MULTIPLE LINES/COMMANDS ON A SINGLE LINE USING ":"
51 PRINT "LINE 50" :PRINT "PLUS SOME STUFF" :PRINT "AND SOME MORE STUFF"

60 END :REM THIS ENDS THE PROGRAM


1000 REM NOTES

1010 REM USING A NEW LINE IN A WINDOWS TEXT EDITOR SEEMS TO COUNT AS A DOUBLE
1011 NEW LINE? BUT NOT IN LINUX... BUG?

1020 REM BASIC WILL SCRUB THE PROCESSING WHITESPACE FOR A LINE AUTOMATICALLY
1021     REM SOME COMMENT
1022 REM SOME COMMENT

1030 REM KEEP LINES UNDER 80 CHARACTERS LONG, OR YOU WILL HAVE TROUBLE LOADING
1031 REM IT IN THE EMULATOR (MIGHT DEPEND ON LOADING METHOD?)
1032 REM (CURRENTLY USING EMULATOR COMMAND TO 'TYPE IN' THE PROGRAM INSTEAD 
1033 REM OF LOADING IT FROM WITHIN THE EMULATED ENVIRONMENT)

